name: gpa_calculator
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.1+4

environment:
  sdk: ^3.0.0


dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flex_color_scheme: ^8.0.2
  flutter_displaymode: ^0.6.0
  flutter_riverpod: ^2.4.0
  fpdart: ^1.1.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  transparent_image: ^2.0.1
  uuid: ^4.0.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  build_runner:
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.6.4
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
