// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIl0_W0cb1zJcJob0UPapgeYFqEPBaVHw',
    appId: '1:1019690643363:android:36ff5a09e19121031a7416',
    messagingSenderId: '1019690643363',
    projectId: 'gpa-calculator-4eb7b',
    storageBucket: 'gpa-calculator-4eb7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAqk4NS5QdsISVYFRLeiffJ74t1168bI',
    appId: '1:1019690643363:ios:47fa3ba1de1168081a7416',
    messagingSenderId: '1019690643363',
    projectId: 'gpa-calculator-4eb7b',
    storageBucket: 'gpa-calculator-4eb7b.appspot.com',
    androidClientId: '1019690643363-6a0s8svpkln5hnp689j3q43jfef1ka4k.apps.googleusercontent.com',
    iosClientId: '1019690643363-7500phj8uavirdg3aa06d3p5emnbl4um.apps.googleusercontent.com',
    iosBundleId: 'com.p0wer.gpaCalculator',
  );

}